### ISSUE TITLE
Are there any published comparisons to other RBFE methods in terms of speed / efficiency?

### ISSUE THREAD

**Issue by DreamCykl** [Gallicchio-Lab/AToM-OpenMM#66] opened 2024-01-04 16:59 UTC
Hi,

I'm very interested by this new and exciting method for computing free energies. I will eventually be testing this project myself, but was wondering whether the authors of this method have done any direct comparisons with other leading FEP methodologies? I'm wondering how it compares in terms of efficiency. For RBFE calcs, since this method only requires 1 simulation (vs 4 for standard RBFEP) it makes sense to me that ATM will be much faster, unless convergence takes 4x as long.

Thanks

**Comment by egallicc** [comment] 2024-01-04 17:32
Thank you. I think there is strong published [evidence](https://www.compmolbiophysbc.org/publications) that ATM is not biased. That is it returns correct free energies conditional on convergence and the system's definition. ATM calls the energy/force routine twice at each time step, so it is at least twice as expensive as MD. However, there isn't much in terms of head-to-head performance comparisons that we know of. One issue is the identification of an available FEP implementation equally unbiased and with the same range of applicability.

**Comment by 9527567** [comment] 2024-01-12 01:31
I printed the speed in the reporter, and to my surprise, the speed slowed down a lot after adding ATMForce, so what I want to know is, is this what should happen?
[std.log](https://github.com/Gallicchio-Lab/AToM-OpenMM/files/13910489/std.log)
[H1Q_H1S_cdk2.log](https://github.com/Gallicchio-Lab/AToM-OpenMM/files/13910491/H1Q_H1S_cdk2.log)
As shown in the [std.log](https://github.com/Gallicchio-Lab/AToM-OpenMM/files/13910489/std.log) file, at the beginning of balancing, the speed is 100ns/day. After adding ATMForce, the speed drops sharply and becomes 18ns/day. [H1Q_H1S_cdk2.log](https://github.com/Gallicchio-Lab/AToM-OpenMM/files/13910491/H1Q_H1S_cdk2.log) shows the speed during the replica exchange process, which becomes lower.

**Comment by egallicc** [comment] 2024-01-14 15:59
Thank you for running this benchmark. The drop in speed from ~90 ns/day to ~18 ns/day during annealing is significantly more than 2x factor expected. I cannot explain it. Can you please share the GPU model you used?

The low replica-exchange performance might be due to the small PRODUCTION_STEPS. Try increasing PRODUCTION_STEPS, PRNT_FREQUENCY, TRJ_FREQUENCY by a factor of 10. The log file indicates a run with multiple GPUs. Make sure that each physical GPU is specified by a different id in the `nodefile`. It would not affect performance, but with a 2 fs time-step HMASS should be 1.0.

**Comment by 9527567** [comment] 2024-01-15 02:12
I used 4 NVIDIA RTX 3090 to run. Due to the use of slurm, it can be ensured that every GPU is utilized, which is also reflected in the information displayed on nvidia-smi. 
Observing the information of nvidia-smi, I can see that the GPU is idle for a considerable amount of time. However, what confuses me is that the speed displayed in the reporter is the speed of the openmm runtime, and the idle time of the GPU will not be counted.
I will add PRODUCTION_STEPS, PRNT_FREQUENCY, TRJ_FREQUENCY to run again.

**Comment by egallicc** [comment] 2024-01-16 14:09
I think the cause of the poor performance has been identified. See OpenMM issue [#4395](https://github.com/openmm/openmm/issues/4395#issue-2084035111). I am not sure how it will be addressed at the moment, but it likely relates to the OpenMM backend.

**Comment by 9527567** [comment] 2024-01-18 08:07
Thank you, I understand. This is a very outstanding job.

**Comment by 9527567** [comment] 2024-01-19 01:27
Thank you, it's very cool!

**Comment by egallicc** [comment] 2024-01-29 20:58
Addressed by the v8.1.1 release.

**Closed by egallicc** 2024-01-29 20:58 UTC
Labels: question
