### ISSUE TITLE
Error: struct.error: unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by vemaparna** [Gallicchio-Lab/AToM-OpenMM#17] opened 2023-01-31 13:01 UTC
Hi! egalicc,
I have been trying RBFE calculations for my set of protein-ligand complexes. i could see this error surfacing with few ligand exchanges, while running the RBFE replica exchange but not for all ligands. The complete error is as follows:

2023-01-31 18:25:30 - INFO     - async_re.openmm_async_re       - UBCORE: 50.0
2023-01-31 18:25:30 - INFO     - async_re.openmm_async_re       - FRICTION_COEFF: 0.500000
2023-01-31 18:25:30 - INFO     - async_re.openmm_async_re       - TIME_STEP: 0.004
2023-01-31 18:25:30 - INFO     - async_re.openmm_async_re       - VERBOSE: no
warning: AddRestraintForce() is deprecated. Use addVsiteRestraintForceCMCM()
warning: AddRestraintForce() is deprecated. Use addVsiteRestraintForceCMCM()
2023-01-31 18:25:31 - INFO     - async_re.openmm_async_re       - Running with a 4.000000 fs time-step with bonded forces integrated 4 times per time-step
2023-01-31 18:25:31 - INFO     - async_re.openmm_async_re       - Worker using Reference OpenMM platform
Traceback (most recent call last):
  File "/home/aparna/Documents/MD/FEP/AToM-OpenMM/rbfe_explicit.py", line 41, in <module>
    rx = openmm_job_AmberRBFE(commandFile, options=None)
  File "/home/aparna/Documents/MD/FEP/AToM-OpenMM/openmm_async_re.py", line 399, in __init__
    replica = OMMReplicaATM(i, self.basename, self.service_worker, self.logger)
  File "/home/aparna/Documents/MD/FEP/AToM-OpenMM/ommreplica.py", line 45, in __init__
    self.open_dcd()
  File "/home/aparna/Documents/MD/FEP/AToM-OpenMM/ommreplica.py", line 92, in open_dcd
    self.dcd = DCDFile(self.dcdfile, self.worker.topology, self.ommsystem.MDstepsize, append=append)
  File "/home/aparna/anaconda3/envs/atom/lib/python3.10/site-packages/openmm/app/dcdfile.py", line 88, in __init__
    self._modelCount = struct.unpack('<i', file.read(4))[0]
struct.error: unpack requires a buffer of 4 bytes

Im totaly new with python programing and i see similar error with other programs in the web. Due to my zero knowledge in programing unable to rectify it. Can you check why this happens to few ligands

**Comment by egallicc** [comment] 2023-01-31 16:30
I have seen this error a few times and I think it was caused by an MD integration failure that generates invalid coordinates. Try to prepare the system more carefully or run it with a smaller MD time-step like 0.001 ps. The error could also potentially be caused by invalid dcd files in the simulation directory from a previous failed run. If so, do `rm -r r? r??` to reset the replica directories.

**Comment by vemaparna** [comment] 2023-02-01 08:32
Thank you.

**Comment by egallicc** [comment] 2023-02-16 01:04
Likely fixed by #18

**Closed by egallicc** 2023-02-16 01:04 UTC
Labels: help wanted
